"""empty message

Revision ID: 901439908b15
Revises: 
Create Date: 2020-07-30 10:49:53.391294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901439908b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_news_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editableHTML',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editor_name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('editor_name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landingimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landingsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=180), nullable=True),
    sa.Column('twitter_name', sa.String(length=25), nullable=True),
    sa.Column('facebook_name', sa.String(length=25), nullable=True),
    sa.Column('instagram_name', sa.String(length=25), nullable=True),
    sa.Column('linkedin_name', sa.String(length=25), nullable=True),
    sa.Column('tiktok_name', sa.String(length=25), nullable=True),
    sa.Column('snap_chat_name', sa.String(length=25), nullable=True),
    sa.Column('youtube', sa.String(length=25), nullable=True),
    sa.Column('blog', sa.String(length=25), nullable=True),
    sa.Column('about', sa.String(length=25), nullable=True),
    sa.Column('contact', sa.String(length=25), nullable=True),
    sa.Column('faq', sa.String(length=25), nullable=True),
    sa.Column('featured_title_one', sa.String(length=90), nullable=True),
    sa.Column('featured_title_one_text', sa.String(length=180), nullable=True),
    sa.Column('featured_title_one_icon', sa.String(length=25), nullable=True),
    sa.Column('featured_title_two', sa.String(length=90), nullable=True),
    sa.Column('featured_title_two_text', sa.String(length=180), nullable=True),
    sa.Column('featured_title_two_icon', sa.String(length=25), nullable=True),
    sa.Column('featured_title_three', sa.String(length=90), nullable=True),
    sa.Column('featured_title_three_text', sa.String(length=180), nullable=True),
    sa.Column('featured_title_three_icon', sa.String(length=25), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=25), nullable=True),
    sa.Column('other_tracking_analytics_one', sa.Text(), nullable=True),
    sa.Column('other_tracking_analytics_two', sa.Text(), nullable=True),
    sa.Column('other_tracking_analytics_three', sa.Text(), nullable=True),
    sa.Column('other_tracking_analytics_four', sa.Text(), nullable=True),
    sa.Column('block_content_one', sa.Text(), nullable=True),
    sa.Column('html_code_one', sa.Text(), nullable=True),
    sa.Column('html_code_two', sa.Text(), nullable=True),
    sa.Column('html_code_three', sa.Text(), nullable=True),
    sa.Column('html_code_four', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about'),
    sa.UniqueConstraint('blog'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('facebook_name'),
    sa.UniqueConstraint('faq'),
    sa.UniqueConstraint('featured_title_one'),
    sa.UniqueConstraint('featured_title_one_icon'),
    sa.UniqueConstraint('featured_title_one_text'),
    sa.UniqueConstraint('featured_title_three'),
    sa.UniqueConstraint('featured_title_three_icon'),
    sa.UniqueConstraint('featured_title_three_text'),
    sa.UniqueConstraint('featured_title_two'),
    sa.UniqueConstraint('featured_title_two_icon'),
    sa.UniqueConstraint('featured_title_two_text'),
    sa.UniqueConstraint('google_analytics_id'),
    sa.UniqueConstraint('instagram_name'),
    sa.UniqueConstraint('linkedin_name'),
    sa.UniqueConstraint('site_name'),
    sa.UniqueConstraint('snap_chat_name'),
    sa.UniqueConstraint('tiktok_name'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('twitter_name'),
    sa.UniqueConstraint('youtube')
    )
    op.create_table('marketplace_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['marketplace_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newslinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_site_one', sa.String(length=25), nullable=True),
    sa.Column('news_site_two', sa.String(length=25), nullable=True),
    sa.Column('news_site_three', sa.String(length=25), nullable=True),
    sa.Column('news_site_four', sa.String(length=25), nullable=True),
    sa.Column('news_site_five', sa.String(length=25), nullable=True),
    sa.Column('news_url_one', sa.String(length=25), nullable=True),
    sa.Column('news_url_two', sa.String(length=25), nullable=True),
    sa.Column('news_url_three', sa.String(length=25), nullable=True),
    sa.Column('news_url_four', sa.String(length=25), nullable=True),
    sa.Column('brand_url_five', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_url_five'),
    sa.UniqueConstraint('news_site_five'),
    sa.UniqueConstraint('news_site_four'),
    sa.UniqueConstraint('news_site_one'),
    sa.UniqueConstraint('news_site_three'),
    sa.UniqueConstraint('news_site_two'),
    sa.UniqueConstraint('news_url_four'),
    sa.UniqueConstraint('news_url_one'),
    sa.UniqueConstraint('news_url_three'),
    sa.UniqueConstraint('news_url_two')
    )
    op.create_table('ourbrands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name_one', sa.String(length=25), nullable=True),
    sa.Column('brand_name_two', sa.String(length=25), nullable=True),
    sa.Column('brand_name_three', sa.String(length=25), nullable=True),
    sa.Column('brand_name_four', sa.String(length=25), nullable=True),
    sa.Column('brand_name_five', sa.String(length=25), nullable=True),
    sa.Column('brand_url_one', sa.String(length=25), nullable=True),
    sa.Column('brand_url_two', sa.String(length=25), nullable=True),
    sa.Column('brand_url_three', sa.String(length=25), nullable=True),
    sa.Column('brand_url_four', sa.String(length=25), nullable=True),
    sa.Column('brand_url_five', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name_five'),
    sa.UniqueConstraint('brand_name_four'),
    sa.UniqueConstraint('brand_name_one'),
    sa.UniqueConstraint('brand_name_three'),
    sa.UniqueConstraint('brand_name_two'),
    sa.UniqueConstraint('brand_url_five'),
    sa.UniqueConstraint('brand_url_four'),
    sa.UniqueConstraint('brand_url_one'),
    sa.UniqueConstraint('brand_url_three'),
    sa.UniqueConstraint('brand_url_two')
    )
    op.create_table('payment_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricingplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('sitesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=128), nullable=True),
    sa.Column('siteaddress', sa.String(length=500), nullable=True),
    sa.Column('administration_user_address', sa.String(length=128), nullable=True),
    sa.Column('site_Language', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('administration_user_address'),
    sa.UniqueConstraint('site_Language'),
    sa.UniqueConstraint('site_title')
    )
    op.create_table('testdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_site_one_1', sa.String(length=25), nullable=True),
    sa.Column('news_site_twi_2', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_site_one_1'),
    sa.UniqueConstraint('news_site_twi_2')
    )
    op.create_table('transactionfees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('local_fee', sa.Integer(), nullable=True),
    sa.Column('european_fee', sa.Integer(), nullable=True),
    sa.Column('international_fee', sa.Integer(), nullable=True),
    sa.Column('transfer_fee', sa.Integer(), nullable=True),
    sa.Column('our_fee', sa.Integer(), nullable=True),
    sa.Column('local_percentage', sa.Float(), nullable=True),
    sa.Column('european_percentage', sa.Float(), nullable=True),
    sa.Column('international_percentage', sa.Float(), nullable=True),
    sa.Column('our_percentage', sa.Float(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('profession', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=6), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('socket_id', sa.Text(), nullable=True),
    sa.Column('online', sa.String(length=1), nullable=True),
    sa.Column('invited_by', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_area_code'), 'users', ['area_code'], unique=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_mobile_phone'), 'users', ['mobile_phone'], unique=True)
    op.create_index(op.f('ix_users_profession'), 'users', ['profession'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_index(op.f('ix_users_zip'), 'users', ['zip'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('spam', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('charge_id', sa.String(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('products_total', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.Column('order_discount', sa.Float(), nullable=True),
    sa.Column('order_pay_amount', sa.Float(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_orders_city'), 'marketplace_orders', ['city'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_country'), 'marketplace_orders', ['country'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_email'), 'marketplace_orders', ['email'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_first_name'), 'marketplace_orders', ['first_name'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_last_name'), 'marketplace_orders', ['last_name'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_mobile_phone'), 'marketplace_orders', ['mobile_phone'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_state'), 'marketplace_orders', ['state'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_zip'), 'marketplace_orders', ['zip'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('lead_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_shipping_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_name'), 'notifications', ['name'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('org_city', sa.String(length=255), nullable=True),
    sa.Column('org_state', sa.String(length=255), nullable=True),
    sa.Column('org_country', sa.String(length=255), nullable=True),
    sa.Column('org_website', sa.String(length=255), nullable=True),
    sa.Column('org_industry', sa.String(length=255), nullable=True),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('blog_post_comments_level_idx', 'blog_post_comments', ['level'], unique=False)
    op.create_index('blog_post_comments_lft_idx', 'blog_post_comments', ['lft'], unique=False)
    op.create_index('blog_post_comments_rgt_idx', 'blog_post_comments', ['rgt'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_cart_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_cart_details_city'), 'marketplace_cart_details', ['city'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_country'), 'marketplace_cart_details', ['country'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_email'), 'marketplace_cart_details', ['email'], unique=True)
    op.create_index(op.f('ix_marketplace_cart_details_first_name'), 'marketplace_cart_details', ['first_name'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_last_name'), 'marketplace_cart_details', ['last_name'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_mobile_phone'), 'marketplace_cart_details', ['mobile_phone'], unique=True)
    op.create_index(op.f('ix_marketplace_cart_details_state'), 'marketplace_cart_details', ['state'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_zip'), 'marketplace_cart_details', ['zip'], unique=False)
    op.create_table('marketplace_product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_seller_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('current_currency_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_seller_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('current_currency_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_shipping_method_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('seller_cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_cart_id'], ['marketplace_seller_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_order_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_total_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['marketplace_seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_order_status_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_order_id', sa.Integer(), nullable=True),
    sa.Column('changed_from', sa.Integer(), nullable=True),
    sa.Column('changed_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['marketplace_seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_order_status_changes')
    op.drop_table('marketplace_order_items')
    op.drop_table('marketplace_cart_items')
    op.drop_table('org_staff')
    op.drop_table('marketplace_shipping_method_prices')
    op.drop_table('marketplace_seller_orders')
    op.drop_table('marketplace_seller_carts')
    op.drop_table('marketplace_product_categories')
    op.drop_index(op.f('ix_marketplace_cart_details_zip'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_state'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_mobile_phone'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_last_name'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_first_name'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_email'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_country'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_city'), table_name='marketplace_cart_details')
    op.drop_table('marketplace_cart_details')
    op.drop_table('logos')
    op.drop_table('blog_post_tags')
    op.drop_index('blog_post_comments_rgt_idx', table_name='blog_post_comments')
    op.drop_index('blog_post_comments_lft_idx', table_name='blog_post_comments')
    op.drop_index('blog_post_comments_level_idx', table_name='blog_post_comments')
    op.drop_table('blog_post_comments')
    op.drop_table('blog_post_categories')
    op.drop_table('subscriptions')
    op.drop_table('photos')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_name'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('marketplace_shipping_methods')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_marketplace_orders_zip'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_state'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_mobile_phone'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_last_name'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_first_name'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_email'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_country'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_city'), table_name='marketplace_orders')
    op.drop_table('marketplace_orders')
    op.drop_table('marketplace_carts')
    op.drop_table('contact_messages')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_users_zip'), table_name='users')
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_index(op.f('ix_users_profession'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_index(op.f('ix_users_area_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('transactionfees')
    op.drop_table('testdb')
    op.drop_table('sitesettings')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('pricingplans')
    op.drop_table('payment_settings')
    op.drop_table('ourbrands')
    op.drop_table('newslinks')
    op.drop_table('marketplace_settings')
    op.drop_table('marketplace_currency')
    op.drop_table('marketplace_categories')
    op.drop_table('landingsettings')
    op.drop_table('landingimages')
    op.drop_table('images')
    op.drop_table('editableHTML')
    op.drop_table('blog_tags')
    op.drop_table('blog_news_letters')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
