"""empty message

Revision ID: 7c0494128ab3
Revises: e9d0fbc3ff57
Create Date: 2020-07-05 00:32:25.088989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0494128ab3'
down_revision = 'e9d0fbc3ff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_site_one', sa.String(length=25), nullable=True),
    sa.Column('news_site_two', sa.String(length=25), nullable=True),
    sa.Column('news_site_three', sa.String(length=25), nullable=True),
    sa.Column('news_site_four', sa.String(length=25), nullable=True),
    sa.Column('news_site_five', sa.String(length=25), nullable=True),
    sa.Column('news_url_one', sa.String(length=25), nullable=True),
    sa.Column('news_url_two', sa.String(length=25), nullable=True),
    sa.Column('news_url_three', sa.String(length=25), nullable=True),
    sa.Column('news_url_four', sa.String(length=25), nullable=True),
    sa.Column('brand_url_five', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_url_five'),
    sa.UniqueConstraint('news_site_five'),
    sa.UniqueConstraint('news_site_four'),
    sa.UniqueConstraint('news_site_one'),
    sa.UniqueConstraint('news_site_three'),
    sa.UniqueConstraint('news_site_two'),
    sa.UniqueConstraint('news_url_four'),
    sa.UniqueConstraint('news_url_one'),
    sa.UniqueConstraint('news_url_three'),
    sa.UniqueConstraint('news_url_two')
    )
    op.create_table('ourbrands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name_one', sa.String(length=25), nullable=True),
    sa.Column('brand_name_two', sa.String(length=25), nullable=True),
    sa.Column('brand_name_three', sa.String(length=25), nullable=True),
    sa.Column('brand_name_four', sa.String(length=25), nullable=True),
    sa.Column('brand_name_five', sa.String(length=25), nullable=True),
    sa.Column('brand_url_one', sa.String(length=25), nullable=True),
    sa.Column('brand_url_two', sa.String(length=25), nullable=True),
    sa.Column('brand_url_three', sa.String(length=25), nullable=True),
    sa.Column('brand_url_four', sa.String(length=25), nullable=True),
    sa.Column('brand_url_five', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name_five'),
    sa.UniqueConstraint('brand_name_four'),
    sa.UniqueConstraint('brand_name_one'),
    sa.UniqueConstraint('brand_name_three'),
    sa.UniqueConstraint('brand_name_two'),
    sa.UniqueConstraint('brand_url_five'),
    sa.UniqueConstraint('brand_url_four'),
    sa.UniqueConstraint('brand_url_one'),
    sa.UniqueConstraint('brand_url_three'),
    sa.UniqueConstraint('brand_url_two')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ourbrands')
    op.drop_table('newslinks')
    # ### end Alembic commands ###
