"""empty message

Revision ID: 95a6dfe9dd67
Revises: 0db3567e61dd
Create Date: 2020-07-05 14:39:20.601204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a6dfe9dd67'
down_revision = '0db3567e61dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testdb', sa.Column('news_site_twi_2', sa.String(length=25), nullable=True))
    op.drop_constraint('testdb_news_site_two_2_key', 'testdb', type_='unique')
    op.create_unique_constraint(None, 'testdb', ['news_site_twi_2'])
    op.drop_column('testdb', 'news_site_two_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testdb', sa.Column('news_site_two_2', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'testdb', type_='unique')
    op.create_unique_constraint('testdb_news_site_two_2_key', 'testdb', ['news_site_two_2'])
    op.drop_column('testdb', 'news_site_twi_2')
    # ### end Alembic commands ###
