"""empty message

Revision ID: aca248e02dd2
Revises: 
Create Date: 2020-07-04 16:59:26.412200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca248e02dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landingpagelogo')
    op.create_foreign_key(None, 'contact_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('landingsettings', sa.Column('featured_title_one', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_one_icon', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_one_text', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_three', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_three_icon', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_three_text', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_two', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_two_icon', sa.String(), nullable=True))
    op.add_column('landingsettings', sa.Column('featured_title_two_text', sa.String(), nullable=True))
    op.drop_constraint('landingsettings_h1_key', 'landingsettings', type_='unique')
    op.drop_constraint('landingsettings_h2_key', 'landingsettings', type_='unique')
    op.drop_constraint('landingsettings_h3_key', 'landingsettings', type_='unique')
    op.drop_constraint('landingsettings_h4_key', 'landingsettings', type_='unique')
    op.drop_constraint('landingsettings_h5_key', 'landingsettings', type_='unique')
    op.create_unique_constraint(None, 'landingsettings', ['youtube'])
    op.drop_column('landingsettings', 'h5')
    op.drop_column('landingsettings', 'h2')
    op.drop_column('landingsettings', 'h3')
    op.drop_column('landingsettings', 'h1')
    op.drop_column('landingsettings', 'h4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landingsettings', sa.Column('h4', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('landingsettings', sa.Column('h1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('landingsettings', sa.Column('h3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('landingsettings', sa.Column('h2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('landingsettings', sa.Column('h5', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.create_unique_constraint('landingsettings_h5_key', 'landingsettings', ['h5'])
    op.create_unique_constraint('landingsettings_h4_key', 'landingsettings', ['h4'])
    op.create_unique_constraint('landingsettings_h3_key', 'landingsettings', ['h3'])
    op.create_unique_constraint('landingsettings_h2_key', 'landingsettings', ['h2'])
    op.create_unique_constraint('landingsettings_h1_key', 'landingsettings', ['h1'])
    op.drop_column('landingsettings', 'featured_title_two_text')
    op.drop_column('landingsettings', 'featured_title_two_icon')
    op.drop_column('landingsettings', 'featured_title_two')
    op.drop_column('landingsettings', 'featured_title_three_text')
    op.drop_column('landingsettings', 'featured_title_three_icon')
    op.drop_column('landingsettings', 'featured_title_three')
    op.drop_column('landingsettings', 'featured_title_one_text')
    op.drop_column('landingsettings', 'featured_title_one_icon')
    op.drop_column('landingsettings', 'featured_title_one')
    op.drop_constraint(None, 'contact_messages', type_='foreignkey')
    op.create_table('landingpagelogo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='landingpagelogo_pkey')
    )
    # ### end Alembic commands ###
