"""empty message

Revision ID: e9d0fbc3ff57
Revises: aca248e02dd2
Create Date: 2020-07-04 18:39:37.641263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d0fbc3ff57'
down_revision = 'aca248e02dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landingsettings', sa.Column('html_code_four', sa.Text(), nullable=True))
    op.add_column('landingsettings', sa.Column('html_code_one', sa.Text(), nullable=True))
    op.add_column('landingsettings', sa.Column('html_code_three', sa.Text(), nullable=True))
    op.add_column('landingsettings', sa.Column('html_code_two', sa.Text(), nullable=True))
    op.add_column('landingsettings', sa.Column('other_tracking_analytics_four', sa.Text(), nullable=True))
    op.add_column('landingsettings', sa.Column('other_tracking_analytics_three', sa.Text(), nullable=True))
    op.drop_constraint('landingsettings_other_tracking_analytics_one_key', 'landingsettings', type_='unique')
    op.drop_constraint('landingsettings_other_tracking_analytics_two_key', 'landingsettings', type_='unique')
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_one'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_one_text'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_one_icon'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_two'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_two_text'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_two_icon'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_three'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_three_text'])
    op.create_unique_constraint(None, 'landingsettings', ['featured_title_three_icon'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.drop_constraint(None, 'landingsettings', type_='unique')
    op.create_unique_constraint('landingsettings_other_tracking_analytics_two_key', 'landingsettings', ['other_tracking_analytics_two'])
    op.create_unique_constraint('landingsettings_other_tracking_analytics_one_key', 'landingsettings', ['other_tracking_analytics_one'])
    op.drop_column('landingsettings', 'other_tracking_analytics_three')
    op.drop_column('landingsettings', 'other_tracking_analytics_four')
    op.drop_column('landingsettings', 'html_code_two')
    op.drop_column('landingsettings', 'html_code_three')
    op.drop_column('landingsettings', 'html_code_one')
    op.drop_column('landingsettings', 'html_code_four')
    # ### end Alembic commands ###
